=== aleksandranedic/xml-project/korisnik/src/main/resources/data/xsd/korisnik.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/jaxb/korisnik"
    xmlns:korisnik="http://www.ftn.uns.ac.rs/jaxb/korisnik">
    <xs:element name="Adresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Ulica">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="100"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Broj" type="xs:positiveInteger"/>
                <xs:element name="Postanski_broj">
                    <xs:simpleType>
                        <xs:restriction base="xs:positiveInteger">
                            <xs:totalDigits value="5"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Grad">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="100"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Drzava">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="100"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Korisnik">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Ime">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="50"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Prezime">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="50"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Email">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[\w\-\.]+@([\w\-]+\.)+[\w\-]{2,4}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Sifra" type="xs:string"/>
                <xs:element name="Uloga">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="Gradjanin|Sluzbenik"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element ref="korisnik:Adresa"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== aleksandranedic/xml-project/korisnik/src/main/resources/data/xml/korisnik.xml
<?xml version="1.0" encoding="UTF-8"?>
<Korisnik xmlns="http://www.ftn.uns.ac.rs/jaxb/korisnik"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/jaxb/korisnik file:/D:/Fourth%20Year/XML%26WebServices/korisnik.xsd">
    <Ime>Miki</Ime>
    <Prezime>Mikic</Prezime>
    <Email>miki@gmail.com</Email>
    <Sifra>sadasdasd</Sifra>
    <Uloga>Sluzbenik</Uloga>
    <Adresa>
        <Ulica>dasd</Ulica>
        <Broj>213</Broj>
        <Postanski_broj>21000</Postanski_broj>
        <Grad>Novi Sad</Grad>
        <Drzava>Srbija</Drzava>
    </Adresa>
</Korisnik>
