=== aleksandranedic/xml-project/autor/src/main/resources/data/xsd/autor.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/jaxb/autor"
    xmlns="http://www.ftn.uns.ac.rs/jaxb/autor">

    <xs:element name="Adresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Ulica" type="xs:string"/>
                <xs:element name="Broj" type="xs:positiveInteger"/>
                <xs:element name="Postanski_broj">
                    <xs:simpleType>
                        <xs:restriction base="xs:positiveInteger">
                            <xs:totalDigits value="5"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Grad" type="xs:string"/>
                <xs:element name="Drzava" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Kontakt">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Telefon">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="06[0-9]{7,8}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="E_posta">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[\w\-\.]+@([\w\-]+\.)+[\w\-]{2,4}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Faks">
                    <xs:simpleType>
                        <xs:restriction base="xs:string"/>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType abstract="true" name="TLice">
        <xs:sequence>
            <xs:element ref="Adresa"/>
            <xs:element ref="Kontakt"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TFizicko_lice">
        <xs:complexContent>
            <xs:extension base="TLice">
                <xs:sequence>
                    <xs:element name="Ime" type="xs:string"/>
                    <xs:element name="Prezime" type="xs:string"/>
                    <xs:element name="Drzavljanstvo" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TPoslovno_lice">
        <xs:complexContent>
            <xs:extension base="TLice">
                <xs:sequence>
                    <xs:element name="Poslovno_ime" type="xs:string"/>
                    <xs:element name="Sediste" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TAutor">
        <xs:complexContent>
            <xs:extension base="TFizicko_lice">
                <xs:sequence>
                    <xs:element name="Godina_smrti" type="xs:date"/>
                    <xs:element name="Znak_autora" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:element name="AutorskoDelo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Naslov" type="xs:string"/>
                <xs:element name="Vrsta" type="xs:string"/>
                <xs:element name="Forma" type="xs:string"/>
                <xs:element name="Podaci_o_naslovu_autorskog_dela" type="TZasnovanoDelo"
                    maxOccurs="1" minOccurs="0"/>
                <xs:element name="Stvoreno_u_radnom_odnosu" type="TEmpty" maxOccurs="1"
                    minOccurs="0"/>
                <xs:element name="Nacin_koriscenja" type="xs:string" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TZasnovanoDelo">
        <xs:sequence>
            <xs:element name="Naslov_autorskog_dela" type="xs:string"/>
            <xs:element name="Ime_autora" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TEmpty"/>
    <xs:element name="Zahtev_za_intelektualnu_svojinu">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Popunjava_podnosilac">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Podnosilac" type="TLice"/>
                            <xs:element name="Punomocnik" type="TLice" minOccurs="0"/>
                            <xs:element maxOccurs="1" minOccurs="1" name="Autori">
                                <xs:complexType>
                                    <xs:choice maxOccurs="unbounded">
                                        <xs:element name="Anoniman" type="TEmpty"/>
                                        <xs:element name="Autor" type="TAutor"/>
                                    </xs:choice>
                                </xs:complexType>
                            </xs:element>
                            <xs:element ref="AutorskoDelo"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Popunjava_zavod">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Broj_prijave">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="A-[0-9]{5}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Datum_podnosenja" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Prilozi_uz_zahtev">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Opis_autorskog_dela" type="xs:string"/>
                            <xs:element name="Primer_autorskog_dela" type="xs:string"/>
                            <xs:element name="Dokaz_o_uplati_takse" type="xs:string"/>
                            <xs:element minOccurs="0"
                                name="Izjava_o_pravno_osnovu_za_podnosenje_prijave" type="xs:string"/>
                            <xs:element minOccurs="0" name="Izjava_o_zajednickom_predstavniku"
                                type="xs:string"/>
                            <xs:element minOccurs="0" name="Punomocje" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Informacija_o_ustanovi">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="Adresa"/>
                            <xs:element name="Naziv">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element minOccurs="0" name="Resenje">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element minOccurs="1" name="Datum" type="xs:dateTime"/>
                            <xs:element name="Status">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Odobren"/>
                                        <xs:enumeration value="Odbijen"/>
                                        <xs:enumeration value=""/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Ime">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Prezime">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Broj_prijave" type="xs:string"/>
                            <xs:element name="Referenca_na_zahtev" type="xs:string"/>
                            <xs:element minOccurs="0" name="Obrazlozenje" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== aleksandranedic/xml-project/autor/src/main/resources/data/xml/a-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Zahtev_za_intelektualnu_svojinu xmlns="http://www.ftn.uns.ac.rs/jaxb/autor"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/jaxb/autor ../xsd/autor.xsd">
    <Popunjava_podnosilac>
        <Podnosilac xsi:type="TFizicko_lice">
            <Adresa>
                <Ulica>Bulevar Kralja Petra</Ulica>
                <Broj>201</Broj>
                <Postanski_broj>11000</Postanski_broj>
                <Grad>Beograd</Grad>
                <Drzava>Republika Srbija</Drzava>
            </Adresa>
            <Kontakt>
                <Telefon>0600000000</Telefon>
                <E_posta>marko@gmail.com</E_posta>
                <Faks>123-00000-000</Faks>
            </Kontakt>
            <Ime>Marko</Ime>
            <Prezime>Markovic</Prezime>
            <Drzavljanstvo>srpsko</Drzavljanstvo>
        </Podnosilac>
        <Autori>
            <Anoniman/>
        </Autori>
        <AutorskoDelo>
            <Naslov>Naslov dela 1</Naslov>
            <Vrsta>vrsta 1</Vrsta>
            <Forma>forma 1</Forma>
            <Podaci_o_naslovu_autorskog_dela>
                <Naslov_autorskog_dela>naslov autorskog dela 2</Naslov_autorskog_dela>
                <Ime_autora>ime autora 2</Ime_autora>
            </Podaci_o_naslovu_autorskog_dela>
            <Stvoreno_u_radnom_odnosu/>
            <Nacin_koriscenja>nacin koriscenja 1</Nacin_koriscenja>
        </AutorskoDelo>
    </Popunjava_podnosilac>
    <Popunjava_zavod>
        <Broj_prijave>A-12353</Broj_prijave>
        <Datum_podnosenja>2004-02-14</Datum_podnosenja>
    </Popunjava_zavod>
    <Prilozi_uz_zahtev>
        <Opis_autorskog_dela>opis_putanja</Opis_autorskog_dela>
        <Primer_autorskog_dela>primer_putanja</Primer_autorskog_dela>
        <Dokaz_o_uplati_takse>dokaz_o_uplati_putanja</Dokaz_o_uplati_takse>
    </Prilozi_uz_zahtev>
    <Informacija_o_ustanovi>
        <Adresa>
            <Ulica>Knjeginje Ljubice</Ulica>
            <Broj>5</Broj>
            <Postanski_broj>11000</Postanski_broj>
            <Grad>Beograd</Grad>
            <Drzava>Republika Srbija</Drzava>
        </Adresa>
        <Naziv>Zavod za intelektualnu svojinu</Naziv>
    </Informacija_o_ustanovi>
</Zahtev_za_intelektualnu_svojinu>
