=== aleksandranedic/xml-project/zig/src/main/resources/data/xsd/zig_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/jaxb/zig"
    xmlns:zig="http://www.ftn.uns.ac.rs/jaxb/zig">

    <xs:element name="Zahtev_za_priznanje_ziga">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Informacije_o_ustanovi">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Naziv">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element ref="zig:Adresa"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Popunjava_podnosilac">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="1" name="Podnosilac" type="zig:TLice"/>
                            <xs:element name="Punomocnik" type="zig:TLice"/>
                            <xs:element name="Zig">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Vrsta">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="Tip_a">
                                                  <xs:complexType>
                                                  <xs:choice>
                                                  <xs:element name="Individualni_zig"
                                                  type="zig:TEmpty" minOccurs="0"/>
                                                  <xs:element name="Kolektivni_zig"
                                                  type="zig:TEmpty" minOccurs="0"/>
                                                  <xs:element name="Zig_garancije" type="zig:TEmpty"
                                                  minOccurs="0"/>
                                                  </xs:choice>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element name="Tip_b">
                                                  <xs:complexType>
                                                  <xs:choice>
                                                  <xs:element name="Verbalni_znak" type="zig:TEmpty"
                                                  minOccurs="0"/>
                                                  <xs:element name="Graficki_znak" type="zig:TEmpty"
                                                  minOccurs="0"/>
                                                  <xs:element name="Kombinovani_znak"
                                                  type="zig:TEmpty" minOccurs="0"/>
                                                  <xs:element name="Trodimenzionalni_znak"
                                                  type="zig:TEmpty" minOccurs="0"/>
                                                  <xs:element name="Druga_vrsta" minOccurs="0">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:minLength value="1"/>
                                                  <xs:maxLength value="20"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>
                                                  </xs:choice>
                                                  </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Naznacenje_boje">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:minLength value="1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element minOccurs="0" name="Transliteracija_znak">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:minLength value="1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element minOccurs="0" name="Prevod_znaka">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:minLength value="1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element minOccurs="0" name="Opis_znaka">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:minLength value="1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Izgled_znaka">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:pattern value="(.+)/([^/]+)"/>
                                                  <xs:minLength value="0"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Dodatne_informacije">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Klasa_robe_i_uslaga">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element maxOccurs="45" name="Klasa">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:positiveInteger">
                                                  <xs:maxInclusive value="45"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Zatrazeno_pravo_prvensta_i_osnov"
                                            type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Placene_takse">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Osnovna_taksa" type="xs:positiveInteger"/>
                                        <xs:element name="Za_klasa">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="Naziv_klase" type="xs:string"/>
                                                  <xs:element name="Suma" type="xs:positiveInteger"
                                                  />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Za_graficko_resenje"
                                            type="xs:positiveInteger"/>
                                        <xs:element name="Ukupno" type="xs:positiveInteger"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Broj_prijave_ziga">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="Z-[0-9]{5}/[0-9]{2}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Datum_podnosenja" type="xs:date"/>
                <xs:element name="Prilozi_uz_zahtev">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="Primerak_znaka" type="xs:string" minOccurs="0"/>
                            <xs:element name="Spisak_robe_i_usluga" type="xs:string" minOccurs="0"/>
                            <xs:element name="Punomocje" type="xs:string" minOccurs="0"/>
                            <xs:element name="Generalno_punomocje" type="xs:string" minOccurs="0"/>
                            <xs:element name="Punomocje_naknadno_dostavljeno" type="xs:string"
                                minOccurs="0"/>
                            <xs:element name="Opsti_akt" type="xs:string" minOccurs="0"/>
                            <xs:element name="Dokaz_o_pravu_prvenstva" type="xs:string"
                                minOccurs="0"/>
                            <xs:element name="Dokaz_o_uplati_takse" type="xs:string" minOccurs="0"/>
                            <xs:element minOccurs="0" name="Resenje" type="xs:string"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="QR_kod" type="xs:string"/>
                <xs:element minOccurs="0" name="Resenje">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element minOccurs="1" name="Datum" type="xs:dateTime"/>
                            <xs:element name="Status">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Odobren"/>
                                        <xs:enumeration value="Odbijen"/>
                                        <xs:enumeration value=""/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Ime">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Prezime">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Broj_prijave" type="xs:string"/>
                            <xs:element name="Referenca_na_zahtev" type="xs:string"/>
                            <xs:element minOccurs="0" name="Obrazlozenje" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Adresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Ulica">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Broj" type="xs:string"/>
                <xs:element name="Postanski_broj">
                    <xs:simpleType>
                        <xs:restriction base="xs:positiveInteger">
                            <xs:minInclusive value="11000"/>
                            <xs:maxInclusive value="40000"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Grad">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="85"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element minOccurs="0" name="Drzava">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="56"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType abstract="true" name="TLice">
        <xs:sequence>
            <xs:element ref="zig:Adresa"/>
            <xs:element ref="zig:Kontakt"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TFizicko_lice">
        <xs:complexContent>
            <xs:extension base="zig:TLice">
                <xs:sequence>
                    <xs:element name="Ime">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="1"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="Prezime">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="1"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TPoslovno_lice">
        <xs:complexContent>
            <xs:extension base="zig:TLice">
                <xs:sequence>
                    <xs:element name="Poslovno_ime" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TEmpty"/>
    <xs:element name="Kontakt">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Email">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[\w\-\.]+@([\w\-]+\.)+[\w\-]{2,4}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Faks">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Telefon">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="(\+381|0)6[0-9]{7,8}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== aleksandranedic/xml-project/zig/src/main/resources/data/xml/z-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xsl-fo/zig.xsl"?>
<Zahtev_za_priznanje_ziga xmlns="http://www.ftn.uns.ac.rs/jaxb/zig"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/jaxb/zig ../xsd/zig_schema.xsd">
    <Informacije_o_ustanovi>
        <Naziv>Zavod za intelektualnu svojinu</Naziv>
        <Adresa>
            <Ulica>Knjeginje Ljubice</Ulica>
            <Broj>5</Broj>
            <Postanski_broj>11000</Postanski_broj>
            <Grad>Beograd</Grad>
        </Adresa>
    </Informacije_o_ustanovi>
    <Popunjava_podnosilac>
        <Podnosilac xsi:type="TFizicko_lice">
            <Adresa>
                <Ulica>Balzakova</Ulica>
                <Broj>19</Broj>
                <Postanski_broj>21000</Postanski_broj>
                <Grad>Novi Sad</Grad>
                <Drzava>Srbija</Drzava>
            </Adresa>
            <Kontakt>
                <Email>sonjas@gmail.com</Email>
                <Faks>584-985-521</Faks>
                <Telefon>0652587456</Telefon>
            </Kontakt>
            <Ime>Sonja</Ime>
            <Prezime>Sonjic</Prezime>
        </Podnosilac>
        <Punomocnik xsi:type="TFizicko_lice">
            <Adresa>
                <Ulica>Strazilovska</Ulica>
                <Broj>23</Broj>
                <Postanski_broj>21000</Postanski_broj>
                <Grad>Novi Sad</Grad>
                <Drzava>Srbija</Drzava>
            </Adresa>
            <Kontakt>
                <Email>miram@gmail.com</Email>
                <Faks>123-456-789</Faks>
                <Telefon>0632548972</Telefon>
            </Kontakt>
            <Ime>Mira</Ime>
            <Prezime>Miric</Prezime>
        </Punomocnik>
        <Zig>
            <Vrsta>
                <Tip_a>               
                    <Individualni_zig/>
                </Tip_a>
                <Tip_b>
                    <Graficki_znak/>
                </Tip_b>
            </Vrsta>
            <Naznacenje_boje> Narandzasta, plava</Naznacenje_boje>
            <Transliteracija_znak > Latinica</Transliteracija_znak>
            <Prevod_znaka >Cirilica</Prevod_znaka>
            <Opis_znaka>Krug sa nazivom firme u sredini</Opis_znaka>
            <Izgled_znaka> C/User/x/home/logo.jpg</Izgled_znaka>
        </Zig>
        <Dodatne_informacije>
            <Klasa_robe_i_uslaga>
                <Klasa>12</Klasa>
                <Klasa>45</Klasa>
            </Klasa_robe_i_uslaga>
            <Zatrazeno_pravo_prvensta_i_osnov > Zatrazeno </Zatrazeno_pravo_prvensta_i_osnov>
        </Dodatne_informacije>
        <Placene_takse>
            <Osnovna_taksa>1000</Osnovna_taksa>
            <Za_klasa>
                <Naziv_klase> 5 </Naziv_klase>
                <Suma>1500</Suma>
            </Za_klasa>
            <Za_graficko_resenje>500</Za_graficko_resenje>
            <Ukupno>3000</Ukupno>
        </Placene_takse>  
    </Popunjava_podnosilac>
    <Broj_prijave_ziga>Z-27190/22</Broj_prijave_ziga>
    <Datum_podnosenja>2022-07-07</Datum_podnosenja>
    <Prilozi_uz_zahtev>
        <Dokaz_o_pravu_prvenstva>dokaz_putanja</Dokaz_o_pravu_prvenstva>
        <Dokaz_o_uplati_takse>dokaz_uplata_putanja</Dokaz_o_uplati_takse>
        <Generalno_punomocje>generalno_punomocje_putanja</Generalno_punomocje>
        <Opsti_akt>opsti_akt</Opsti_akt>
    </Prilozi_uz_zahtev>
    <QR_kod></QR_kod>
</Zahtev_za_priznanje_ziga>
